apiVersion: apps/v1
kind: Deployment
metadata:
  name: mama
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mama
  template:
    metadata:
      labels:
        app: mama
    spec:
      containers:
      - name: mama
        image: your-docker-username/image3
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mama
spec:
  selector:
    app: mama
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer
