apiVersion: apps/v1
kind: Deployment
metadata:
  name: web/app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web/app
  template:
    metadata:
      labels:
        app: web/app
    spec:
      containers:
      - name: web/app
        image: ganeshnalli/image3:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web/app
spec:
  selector:
    app: web/app
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer
